// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sgokul961/echo-hub-post-svc/pkg/api"
	"github.com/sgokul961/echo-hub-post-svc/pkg/api/handler"
	"github.com/sgokul961/echo-hub-post-svc/pkg/client"
	"github.com/sgokul961/echo-hub-post-svc/pkg/config"
	"github.com/sgokul961/echo-hub-post-svc/pkg/db"
	"github.com/sgokul961/echo-hub-post-svc/pkg/repository"
	"github.com/sgokul961/echo-hub-post-svc/pkg/usecase"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.Init(cfg)
	if err != nil {
		return nil, err
	}
	postRepoInterface := repository.NewPostRepo(gormDB)
	authServiceClient := client.NewAuthServiceClient(cfg)
	chatServiceClient := client.NewChatServiceClient(cfg)
	postUseCaseInterface := usecase.NewPostUseCase(postRepoInterface, authServiceClient, chatServiceClient)
	postHandler := handler.NewPostHandler(postUseCaseInterface)
	serverHTTP := api.NewServerHttp(postHandler)
	return serverHTTP, nil
}
